import OpenAIIcon from "@/support/icons/OpenAIIcon";
import AnthropicIcon from "./icons/AnthropicIcon";
import GoogleIcon from "./icons/GoogleIcon";
import DeepseekIcon from "./icons/DeepseekIcon";

const models = [
  {
    id: "openai/gpt-4.1",
    name: "GPT 4.1",
    description: "Latest model",
    icon: OpenAIIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "gpt-4.1",
  },
  {
    id: "openai/gpt-4.1-mini",
    name: "GPT 4.1 Mini",
    description: "Mini model",
    icon: OpenAIIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: false,
    originalId: "gpt-4.1-mini",
  },
  {
    id: "openai/gpt-4.1-nano",
    name: "GPT-4.1 Nano",
    description: "Nano model",
    icon: OpenAIIcon,
    available: true,
    docsUpload: false,
    imageUpload: false,
    premium: false,
    originalId: "gpt-4.1-nano",
  },
  {
    id: "openai/gpt-4o-2024-11-20",
    name: "GPT-4o",
    description: "Latest model",
    icon: OpenAIIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "gpt-4o",
  },
  {
    id: "openai/gpt-4o-mini",
    name: "GPT-4o Mini",
    description: "Mini model",
    icon: OpenAIIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: false,
    originalId: "gpt-4o-mini",
  },
  {
    id: "openai/gpt-image-1",
    name: "GPT Image 1",
    description: "Image generation model",
    icon: OpenAIIcon,
    available: true,
    docsUpload: false,
    imageUpload: true,
    premium: true,
    originalId: "gpt-image-1",
  },
  {
    id: "anthropic/claude-sonnet-4",
    name: "Claude 4 Sonnet",
    description: "Pro feature",
    icon: AnthropicIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "claude-sonnet-4-20250514",
  },
  {
    id: "anthropic/claude-3.7-sonnet",
    name: "Claude 3.7 Sonnet",
    description: "Pro feature",
    icon: AnthropicIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "claude-3-7-sonnet-20250219",
  },
  {
    id: "anthropic/claude-3.7-sonnet:thinking",
    name: "Claude 3.7 Sonnet: Thinking",
    description: "Pro feature",
    icon: AnthropicIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "claude-3-7-sonnet-20250219",
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    description: "Pro feature",
    icon: AnthropicIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "claude-3-5-sonnet-20241022",
  },
  {
    id: "anthropic/claude-3-haiku",
    name: "Claude 3 Haiku",
    description: "Pro feature",
    icon: AnthropicIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: false,
    originalId: "claude-3-5-haiku-20241022",
  },
  {
    id: "google/gemini-2.5-pro-preview",
    name: "Gemini 2.5 Pro",
    description: "Latest model",
    icon: GoogleIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: true,
    originalId: "gemini-2.5-pro-preview-06-05",
  },
  {
    id: "google/gemini-2.5-flash-preview-05-20",
    name: "Gemini 2.5 Flash",
    description: "Fast responses",
    icon: GoogleIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: false,
    originalId: "gemini-2.5-flash-preview-05-20",
  },
  {
    id: "google/gemini-2.5-flash-preview-05-20:thinking",
    name: "Gemini 2.5 Flash: Thinking",
    description: "Fast responses",
    icon: GoogleIcon,
    available: true,
    docsUpload: true,
    imageUpload: true,
    premium: false,
    originalId: "gemini-2.5-flash-preview-05-20",
  },
  {
    id: "google/gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash",
    description: "Fast responses",
    icon: GoogleIcon,
    available: true,
    docsUpload: false,
    imageUpload: false,
    premium: false,
    originalId: "gemini-2.0-flash",
  },
  {
    id: "google/gemini-2.0-flash-lite-001",
    name: "Gemini 2.0 Flash Lite",
    description: "Fast responses",
    icon: GoogleIcon,
    available: true,
    docsUpload: false,
    imageUpload: false,
    premium: false,
    originalId: "gemini-2.0-flash-lite",
  },
  {
    id: "deepseek/deepseek-r1-0528",
    name: "DeepSeek R1",
    description: "Reasoning model",
    icon: DeepseekIcon,
    available: true,
    docsUpload: false,
    imageUpload: false,
    premium: false,
    originalId: "deepseek/deepseek-chat-v3-0324",
  },
  {
    id: "deepseek/deepseek-chat-v3-0324",
    name: "DeepSeek Chat V3",
    description: "Reasoning model",
    icon: DeepseekIcon,
    available: true,
    docsUpload: false,
    imageUpload: false,
    premium: false,
    originalId: "deepseek/deepseek-chat-v3-0324",
  },
];

export default models;
